import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const useLink = [
    { link: "/home", text: "Home" },
    { link: "/about", text: "About" },
    { link: "/services", text: "Services" },
    { link: "/Portfolio", text: "Portfolio" },
    { link: "/projects", text: "Projects" },
    { link: "/contact", text: "Contact" },
  ];
  return (
    <html lang="en" className="h-full">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased h-full`}>
        <div className="container-fluid mx-auto h-full">
          <div className="flex h-[calc(100vh-65px)]">
            <div className="w-1/12 bg-[#f7f6f1] border-r border-black text-black p-6 shadow-md">
              Footer
            </div>
            <div className="w-11/12 bg-[#f7f6f1] text-black p-6 shadow-md">
              {children}
            </div>
          </div>
          <div className="flex">
            <div className="w-12/12 bg-[#f7f6f1] border-t border-black text-white">
              <ul className="flex">
               {
                useLink.map((linkData,index)=>(
                  <li key={index} className="w-full p-5 border-r border-black text-center">
                    <a href={linkData.link} className="text-black flex items-center justify-center h-full">
                      {linkData.text} <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="none" stroke="currentColor" stroke-width="2" d="M6 12.4h12M12.6 7l5.4 5.4l-5.4 5.4"/></svg>
                    </a>
                  </li>
                ))
               }
              </ul>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
